name: Generate

on:
  push:
    branches:
      - '**'
    paths:
      - messages/**

jobs:
  generate:
    name: Generate Feeds & Indexes
    runs-on: ubuntu-20.04

    steps:
      - name: checkout.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate the feeds.
        run:  bash bin/generate-latest-feed.sh

      - run: echo "$PRIVATE_KEY" > ssh_key && chmod 600 ssh_key
        shell: bash
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      
      - run: echo "$PUBLIC_KEY" > ssh_key.pub
        shell: bash
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      
      - name: Generate messages.
        run:  bash bin/generate-post-messages.sh
        env:
          STATIC_HOSTNAME: ${{ secrets.STATIC_HOSTNAME }}
          AUTHOR: ${{ secrets.AUTHOR }}
          PRIVATE_KEY: ssh_key.pub

      - name: Generate messages.
        run:  bash bin/index-feeds.sh

      - name: Add any feeds files.
        run: '[[ -f ./docs/feeds.list ]] &&  git add ./docs/feeds.list'

      - name: Add any feeds files.
        run: '[[ -f ./docs/peers.list ]] &&  git add ./docs/feeds.list'

      - name: Add any feeds files.
        run:  git add ./docs/feeds/**

      - name: Add any message files.
        run:  git add ./docs/messages/**

      - name: Commit & push any if changes are found
        run:  |
          test -n "$(git status -s)" \
            && git \
              -c "user.name=index-bot" \
              -c "user.email=index-bot@seanmorr.is" \
              commit -nam 'Indexing messages.' \
            && git push \
            || true
