name: Generate

on:
  push:
    branches:
      - '**'
    paths:
      - content/**

jobs:
  index-content:
    name: Generate Feeds
    runs-on: ubuntu-20.04

    steps:
      - name: checkout.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Generate the feeds.
        run:  bash bin/generate-latest-feed.sh

      - run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        shell: bash
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      
      - name: Generate messages.
        run:  bash bin/generate-post-messages.sh
        env:
          STATIC_HOSTNAME: https://sycamore.seanmorr.is
          AUTHOR: 'Sean Morris <sean@seanmorr.is>'
          PRIVATE_KEY: private_key

      - name: Add any feeds files.
        run:  git add ./docs/feeds/**

      - name: Add any message files.
        run:  git add ./docs/messages/**

      - name: Commit & push any if changes are found
        run:  |
          test -n "$(git status -s)" \
            && git \
              -c "user.name=index-bot" \
              -c "user.email=index-bot@seanmorr.is" \
              commit -nam 'Indexing content.' \
            && git push \
            || true
