name: Generate Messages

on:
  push:
    branches:
      - '**'
    paths:
      - content/**

jobs:
  index-content:
    name: Generate Messages
    runs-on: ubuntu-18.04

    steps:
      - name: checkout.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate the message.
        run:  bash bin/generate-post-messages.sh

      - name: Add any message files.
        run:  git add ./docs/messages/**

      - name: Commit & push any if changes are found
        run:  |
          test -n "$(git status -s)" \
            && git \
              -c "user.name=index-bot" \
              -c "user.email=index-bot@seanmorr.is" \
              commit -nam 'Indexing content.' \
            && git push \
            || true
